### ISSUE TITLE
'Other' radio option labels

### ISSUE THREAD

**Issue by gyrus** [ovann86/gravity-forms-wcag-20-form-fields#2]
It's great to have fieldset / legend for radio groups :-)  However, there's an issue with the 'Other' radio option. Both the 'Other' radio input and the associated text input lack labels.

This is something I came up with a hack for, though it may need improvement. I'll wait til the latest code is here to submit a pull request.

**Comment by ovann86** [comment]
Hi gyrus,

I'm working on fixing this and a few other bugs in this plugin today.

Did you have any suggestions on how this should be achieved?

A quick search makes me think that 'other' options in radio lists don't even meet the HTML spec, so it'll be hard/impossible so make it pass the tests and make accessible. (I could be wrong here, happy to be shown otherwise).

I'm thinking about adding in a hidden label of 'Other' for the text input. not sure if it'll break anything else though.

(Note  - github still isnt the latest version, the WordPress SVN has the latest version. I plan to keep these up to date in the future).

**Comment by ovann86** [comment]
Hi again,

I've managed to set this up, it passes WCAG 2.0 - AA using HTML_CodeSniffer (http://squizlabs.github.io/HTML_CodeSniffer/) and tested find using JAWS and Firefox.

I had to insert labels for both the 'other' radio and input fields, and modify the jQuery that these fields uses to control the focus (they were explicitly using 'next' and 'previous' which broke as soon as I inserted a label between them).

The labels have the sr-only class, so will only be read out for screen reader users.

Will push out the update later in the day.

**Comment by gyrus** [comment]
Many thanks, this looks good!

For the record, this was my hack, along similar lines:

```
add_filter( 'gform_field_content', 'pilau_gform_field_content', 10, 5 );
function pilau_gform_field_content( $content, $field, $value, $lead_id, $form_id ) {

	// Check for 'other' radios that need labels adding
	if ( $field->type == 'radio' ) {
		foreach ( $field->choices as $choice ) {
			if ( $choice['value'] == 'gf_other_choice' ) {
				$content = preg_replace( "#<input[ ]+name='([^']+)'[ ]+type='([^']+)'[ ]+value='gf_other_choice'[ ]+id='([^']+)'#", '<label class=\'screen-reader-text\' for=\'\3\'>Other</label> <input name=\'\1\' type=\'\2\' value=\'gf_other_choice\' id=\'\3\'', $content );
				$content = preg_replace( "#<input[ ]+id='input_([0-9]+)_([0-9]+)_other'#", '<label class=\'screen-reader-text\' for=\'input_\1_\2_other\'>Please enter other value here</label> <input id=\'input_\1_\2_other\'', $content );
			}
		}
	}

	return $content;
}
```
